name: Scaleindia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_auth: ^0.20.1
  cloud_firestore: ^0.16.0+1
  firebase_storage: ^7.0.0
  shared_preferences: ^0.5.12
  image_cropper: ^1.4.0
  firebase_core: ^0.7.0
  get_it: ^6.0.0
  http: ^0.12.2
  provider: ^4.3.2+1
  stacked_services: ^0.7.2
  provider_architecture: ^1.1.1+1
  curved_navigation_bar: ^0.3.4
  stacked: ^1.7.6
  async: ^2.4.1
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  connectivity: ^3.0.2
  flutter_offline: ^2.0.0
  image_picker: ^0.6.7+21
  slide_countdown_clock: ^1.0.3
  flutter_svg: ^0.19.0
  simple_pdf_viewer: ^0.2.2
  flutter_launcher_icons: ^0.8.1
  firebase_ml_vision: ^0.11.0
  path_provider: ^1.6.24
  camera: ^0.5.8+17
  image: ^2.1.19
  tflite_flutter: ^0.5.0
  path: ^1.7.0
  workmanager: ^0.2.3
  flutter_local_notifications: ^4.0.1+2
  audioplayers: ^0.17.4
  geolocator: ^6.1.13
  geocoder: ^0.2.1
  permission_handler: ^5.0.1+1
  agora_rtc_engine: ^3.2.1
  pinput: ^1.1.0
  dio:
  progress_dialog:
  flutter_full_pdf_viewer: ^1.0.6
  cached_network_image: ^2.5.0
  video_compress: ^2.1.1
  file_picker: ^1.13.0+1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  image_path: 'assets/img/scale_india.png'
  android: true
  ios: true    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/img/logo.png
   - assets/img/boy1.png
   - assets/img/
   - assets/mobilefacenet.tflite
   - assets/
   
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: assets/font/avenir.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
